name: Dev Deploy

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: mskelton/setup-yarn@v1
        with:
          node-version: 16.x

      - name: Build
        run: yarn build

      - name: Deploy
        uses: lbertenasco/s3-deploy@v1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        with:
          folder: dist
          bucket: ${{ secrets.AWS_S3_DEV_BUCKET }}
          dist-id: ${{ secrets.AWS_CLOUDFRONT_DEV_DISTRIBUTION_ID }}
          invalidation: "/*"